### PR TITLE
Build OpenMC from source in GH Actions workflow

### LINKED ISSUE #151: [Meta] Merge order for open PRs
Figuring out a workaround to the HDF5 conflict between PyNE and OpenMC took some time. Now that I have figured it out, there are several PRs that need to get merged. They should be merged in the following order.

1. #150 
2. #132
3. #144
4. #137

### PR DESCRIPTION
**Pull request by yardasol**
## Summary of changes

This PR adds the capability to build OpenMC from source in our Github Actions workflows so that we can have OpenMC v0.13.0 and Pyne installed in the same environment.

We need to do this because there is a dependency conflict between the `conda-forge` builds of OpenMC v0.13.0 and Pyne. This conflict has held up #132.

Note that this is a temporary measure and is not an ideal long term solution due to the increased time it takes for the workflow to run. Hopefully with caching we can reduce the load a bit.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Required for Merging
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly. -> in a separate PR #144 
- [ ] My change is a source code change
  - [ ] I have added/modified tests to cover my changes
  - [ ] I have explained why my change does not require new/modified tests
- [x] My change is a user-facing change
  - [x] I have recorded my changes in the changelog for the upcoming release
- [x] My change is exclusively related to the repository (e.g. GitHub actions workflows, PR/issue templates, etc.)
  - [x] I have verified or justified that my change will work as intended. -> see [this workflow run](https://github.com/yardasol/saltproc/actions/runs/2066775217/attempts/1) 
- [x] All new and existing tests passed.
  - [x] CI tests pass
  - [x] Local tests pass (including Serpent2 integration tests)
## Associated Issues and PRs

- Issue: workaround for [1443 in pyne
](https://github.com/pyne/pyne/issues/1443)
See also the [relevant post on the OpenMC forums](https://openmc.discourse.group/t/request-for-a-build-of-openmc-0-13-0-with-hdf5-1-10-6/1862/3)

- Issue: partially resolved #151 

## Associated Developers

- Dev: @munkm 

## Checklist for Reviewers

Reviewers should use [this link](https://arfc.github.io/manual/guides/pull_requests) to get to the 
Review Checklist before they begin their review.

### CODE REVIEW

**Review by abachma2 — COMMENTED** [review]
This looks good to me. Do you have any tests to make sure this runs properly?

**Comment by yardasol** [comment]
> This looks good to me. Do you have any tests to make sure this runs properly?

No tests, but I do have a workflow. I linked to it at the bottom of the OpenMC forums post.

**Comment by abachma2** [comment]
Do you need to add in any tests? Have you verified that this workflow will work as expected?

**Comment by yardasol** [comment]
> Do you need to add in any tests? Have you verified that this workflow will work as expected?

To my knowledge, the only way to test a workflow is to run it. If you look at the "Checks" tab, you'll see that my proposed changes are indeed working (GH will run the modified workflow in the PR instead of the one on `master`)

**Comment by abachma2** [comment]
I missed that link in the PR body. I will approve and merge this then!

**Review by abachma2 — APPROVED** [review]

**Pull request merged**
