### PR TITLE
Refactor depcode

### PR DESCRIPTION
**Pull request by yardasol**
This PR changes the structure of the `Depcode` class to use python's [Abstract Base Class](https://docs.python.org/3/library/abc.html) to make the changes outlined in #59 .

This PR also adjusts the import statements in the test suite to match the new class names.

### CODE REVIEW

**Review by LukeSeifert — COMMENTED** [review]
Looks good! Everything seems to be working as well when I ran it with the msbr example case (had to change Andrei's cross section locations to my own and create an empty "data" directory in saltproc, but had to do that before anyways).

**Comment by yardasol** [comment]
@gwenchee @LukeSeifert @munkm I believe I've addressed all requested changes, so if there aren't any more issues could one of you approve so we can merge?

**Review by gwenchee — APPROVED** [review]
You haven't addressed the `moment` comment we discussed above but besides that LGTM!

**Comment by yardasol** [comment]
@gwenchee did you see my follow up comment about that?

> Update: moment is used to slice arrays when processing materials, so it makes sense that it's an integer.

I guess since we are only every using 0 or 1 as the value for `moment`, it does make sense to change it to a boolean and then add an `if`-statement in the body of `read_dep_comp`. I'll make a commit for this

**Pull request merged**
